### PR TITLE
fixed region issue

### LINKED ISSUE #92: Region is ignored while pulling
`dogestry pull 's3://foo-bar/?region=eu-west-1' foo:2015-11-30T11.46.59.190Z.2de802a`

got this error:
```
Errors during getFiles:
map[images/75dc35548036ee0dac9587d690d0d1da5de7609e245ba29585ccad6ac44cd248/VERSION:400: 
"The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'"
images/75dc35548036ee0dac9587d690d0d1da5de7609e245ba29585ccad6ac44cd248/json:400: 
"The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'"
images/75dc35548036ee0dac9587d690d0d1da5de7609e245ba29585ccad6ac44cd248/layer.tar:400:
"The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'"]
```
2.0.2 everything works fine

### PR DESCRIPTION
**Pull request by dselans**
s3gof3r was updated to determine the region based on the domain it was instantiated with in .New().
We have always set this to "", however the new change made this become "us-east-1" by default.

This commit:

- updates the s3gof3r instantiation logic
- adds a new Region attribute to the Config struct, which can then be utilized
for instantiating other S3 handlers (goamz or s3gof3r)

@talpert @idleyoungman 

Fixes #92

### CODE REVIEW

File: remote/s3.go [hunk 1]
```diff
@@ -232,8 +244,8 @@ func (remote *S3Remote) WalkImages(id ID, walker ImageWalkFn) error {
 func (remote *S3Remote) ImageMetadata(id ID) (docker.Image, error) {
 	bucket := remote.getBucket()
 	image := docker.Image{}
-	
-	files := []string{ "json", "layer.tar", "VERSION" }
+
+	files := []string{"json", "layer.tar", "VERSION"}
```
Comment (dselans) [inline remote/s3.go]: go fmt...

**Comment by talpert** [comment]
:shipit:
